#!/bin/bash
echo "=== Starting ArcoLinux update: $(date) ===" >>~/bin/logs/arcolinux-update.log

paru -Syyu --noconfirm >>~/bin/logs/arcolinux-update.log 2>&1

echo "=== Finished: $(date) ===" >>~/bin/logs/arcolinux-update.log
